<style type="text/css">
a{ color:#333; text-decoration:underline}
a:hover{ color:#0ff; text-decoration:none}
</style>
<table width="762" border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF" class="style1">
  <tr>
    <td align="left">
	<a href="../tdl/index.asp" onfocus='this.blur()'><img src="../tdl/image/logo_mini39.gif" border="0"></a>
	<a href="../crm/index.asp" onfocus='this.blur()'><img src="../crm/image/logo_mini39.gif" border="0"></a>
	<a href="http://www.webmama.cn">妈妈网首页</a>
    </td>
    <td align="right" valign="bottom">
        <a href="buy.asp" onfocus='this.blur()'><img src="image\top1.gif" border="0" alt="商品入库"></a>
        <a href="sell.asp" onfocus='this.blur()'><img src="image\top2.gif" border="0" alt="卖出商品"></a>
        <a href="seat.asp" onfocus='this.blur()'><img src="image\top3.gif" border="0" alt="仓位整理"></a>
	<a href="return.asp" onfocus='this.blur()'><img src="image\top4.gif" border="0" alt="退货"></a>
        <a href="postage.asp" onfocus='this.blur()'><img src="image\top5.gif" border="0" alt="邮费录入"></a>
	<a href="admin_system.asp" onfocus='this.blur()'><img src="image\top6.gif" border="0" alt="修改密码和杂项"></a>
	<a href="admin_inquire.asp" onfocus='this.blur()'><img src="image\top7.gif" border="0" alt="查询和导出报表"></a>
	<a href="admin_statistics.asp" onfocus='this.blur()'><img src="image\top8.gif" border="0" alt="利润统计"></a>
    </td>
  </tr>
</table>